yetanalytics/dave

src/com/yetanalytics/dave/ui/app/workbook.cljs, src/com/yetanalytics/dave/ui/app/workbook/data.cljs, src/com/yetanalytics/dave/ui/views/workbook.cljs, src/com/yetanalytics/dave/ui/views/workbook/data.cljs, src/com/yetanalytics/dave/workbook/data.cljc
Small display ui element for dataset/source. Added a concept of errors for data (retrieval, etc).
Workbook data source should show on the workbook page.
=> added errors to data spec, and wrote basic ui to show data src

src/com/yetanalytics/dave/func.cljc, src/com/yetanalytics/dave/ui/app/workbook/question.cljs, src/com/yetanalytics/dave/ui/app/workbook/question/func.cljs, src/com/yetanalytics/dave/ui/events.cljs, src/com/yetanalytics/dave/ui/views/workbook/question.cljs, src/com/yetanalytics/dave/ui/views/workbook/question/func.cljs
Add display information to DAVE functions, and some info for callers on the args (defaults, enums)
Add a simple ui element for displaying a function on a question page
=> Func display

deps.edn, src/com/yetanalytics/dave/func.cljc, src/com/yetanalytics/dave/func/ret.cljc, src/com/yetanalytics/dave/func/util.cljc
Initial implementation of the "follow recommendations" function from DAVE section 5
=> 5 recommendations func

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views/workbook/question.cljs
=> Added Visualizations heading title

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/func.cljc, src/com/yetanalytics/dave/func/ret.cljc, src/com/yetanalytics/dave/func/util.cljc, src/com/yetanalytics/dave/ui/app/picker.cljs, src/com/yetanalytics/dave/ui/app/vega.cljs, src/com/yetanalytics/dave/ui/app/workbook.cljs, src/com/yetanalytics/dave/ui/app/workbook/data.cljs, src/com/yetanalytics/dave/ui/app/workbook/question/func.cljs, src/com/yetanalytics/dave/ui/core.cljs, src/com/yetanalytics/dave/ui/views/picker.cljs, src/com/yetanalytics/dave/ui/views/root.cljs, src/com/yetanalytics/dave/ui/views/vega.cljs, src/com/yetanalytics/dave/ui/views/workbook.cljs, src/com/yetanalytics/dave/ui/views/workbook/question/visualization.cljs, src/com/yetanalytics/dave/workbook.cljc, src/com/yetanalytics/dave/workbook/question/visualization.cljc
Theres also some formatting from the parenfer add on.
=> Added styling for the function section on the page before visualization

resources/dave/ui/sass/nav.scss, resources/dave/ui/sass/style.scss, src/com/yetanalytics/dave/ui/views/workbook.cljs
I decided to commit while was ahead. 
So I found out how to do this without editing the other grids! 💯
=> Fixed the grid for the dataset

.gitignore, deps.edn, prod.cljs.edn, resources/public/prod_index.html, scripts/gh_pages.sh, src/com/yetanalytics/dave/ui/core.cljs, src/com/yetanalytics/dave/ui/views.cljs, src/com/yetanalytics/dave/ui/views/nav.cljs
Creates a production build suitable for github pages.
TODO:
=> Prod build

README.md, deps.edn, src/com/yetanalytics/dave.cljc, src/com/yetanalytics/dave/func.cljc, src/com/yetanalytics/dave/func/common.cljc, src/com/yetanalytics/dave/func/util.cljc, src/com/yetanalytics/dave/util/spec.cljc, test.cljs.edn, test/com/yetanalytics/dave/func/common_test.cljc, test/com/yetanalytics/dave/func/util_test.cljc, test/com/yetanalytics/dave/func_test.cljc, test/com/yetanalytics/dave/test_runner.cljs, test/com/yetanalytics/dave/test_support.cljc, test/com/yetanalytics/dave_test.cljc, test/com/yetanalytics/dave_test.cljs
Add facilities to run Clojure(Script) tests. Generative testing implemented for core DAVE functions.
=> Test runner

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views/root.cljs, src/com/yetanalytics/dave/ui/views/workbook.cljs, src/com/yetanalytics/dave/ui/views/workbook/question.cljs
These stylings add to the "New Workbook, New Question, New Visualization" buttons. I did this by adding a new class "newblock" to each button element and styling it.
=> Added styling to 'New ____' buttons

src/com/yetanalytics/dave/ui/views/workbook/question.cljs, src/com/yetanalytics/dave/ui/views/workbook/question/visualization.cljs
Ah I see, I shoulve made a new branch **before** changing the vis button styling, which accounts for the double PRs. But thats what they both are for. Styling for the edit / delete buttons on both pages.
=> Vispagebutton

resources/dave/ui/sass/nav.scss
Just added some shadows to the "new" workbook, questions visualization buttons.
=> Newbuttonstyling

resources/dave/ui/sass/wizard.scss, src/com/yetanalytics/dave/ui/views/wizard.cljs
The last three commits 
2d657de
108547d
cc01228
=> Wizardstyling

resources/dave/ui/sass/wizard.scss, src/com/yetanalytics/dave/ui/views/wizard.cljs
Hey Milt! 
Before when you picked a vis this box would grow according to that visualizations size. This gives it a max so that it won't adjust.
=> Made the vis preview box a max height

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/app/nav.cljs, src/com/yetanalytics/dave/ui/views/workbook.cljs, src/com/yetanalytics/dave/ui/views/workbook/question.cljs, src/com/yetanalytics/dave/ui/views/workbook/question/visualization.cljs
This took some effort. I cleaned up the code a bit. The first bit in nav.scss is the style changes. 
I also had to fix some class titles because some divs had incorrect class titles.
=> Added styling to workbook selection home page

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views/workbook.cljs
The 429a989 was just removing a class I didnt need.
=> Navigationdesign

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views/workbook/question.cljs, src/com/yetanalytics/dave/ui/views/workbook/question/visualization.cljs
For child cells in workbooks (questions, visualizations), removes the buttons and makes the title a link (for tabability/accessibility). The existing on-click action for the entire cell takes care of navigation.
=> removed nav buttons, make titles links

resources/dave/ui/sass/wizard.scss, src/com/yetanalytics/dave/ui/views/wizard.cljs
I CSS'd my way through this. Its fixed. I want to continue iterating over this to make it cleaner code, but this does work.
=> Aligned the buttons in the Wizard

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views.cljs, src/com/yetanalytics/dave/ui/views/nav.cljs
Hey Milt, I added in the footer which is on the list of items to complete for DAVE. I kept it pretty simple, and also created 12 new workbooks to make sure nothing would be overlapped by the footer. The footer also links to the homepage.
=> Added footer which links back to the homepage

resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views/dialog.cljs
Use f2709f0. I just updated a small color portion.
=> Wizardnavdesign

CHANGELOG.md, resources/dave/ui/sass/mdc.scss, resources/dave/ui/sass/nav.scss, src/com/yetanalytics/dave/ui/views/dialog.cljs
Here are the updates we discussed with the updates to the ChangeLog!
=> Fixed wizard navigation buttons

CHANGELOG.md, src/com/yetanalytics/dave/vis.cljc, src/com/yetanalytics/dave/vis/scatter.cljc
This PR adds a scatter plot where the x axis is time, the y axis is categorical ("lane-style"), and catregory is required.
=> initial version of time scatter plot w/point axis

README.md
Readme update to point at new documents
=> Update to include links to Primitives work

src/com/yetanalytics/dave/datalog.cljc, src/com/yetanalytics/dave/datalog/schema.cljc, test/com/yetanalytics/dave/datalog_test.cljc
Collapsed as many component entities in the schema as I could. Queries are a little uglier, performance is way better.
=> compacted schema for better xapi domain compression

src/com/yetanalytics/dave/datalog/builtins.cljc, src/com/yetanalytics/dave/datalog/rules.cljc
Integrating Cliff's work on Query functions
=> math rules from js/Math

CHANGELOG.md, QUERY.md, README.md
Updated READMEs and added a new one for query syntax
=> Readme docs update

deps.edn
Needed a vega upgrade to account for some missing visualizations
=> Vega upgrade

resources/dave/ui/sass/buttons.scss, src/com/yetanalytics/dave/ui/views/workbook/analysis.cljs
CSS affects the Import and Export buttons
=> Minimalbutton
